# Day 4: Sorting and Filtering with Multiple Conditions

Today's new concept builds on the filtering you already know (`df[df["score"] >= threshold]`).

We'll cover:
1. Combining multiple conditions with `&`, `|`, `~`
2. Sorting results with `.sort_values()`
3. Practice exercises

We'll also mix in quick reviews of what you learned in Day 3 (dtypes, `.iterrows()`, `.groupby()`).

## Setup

Run this first to create the sample DataFrame we'll use throughout.

In [12]:
import pandas as pd

df = pd.DataFrame({
    "name": ["Ali", "Sara", "Omar", "Lina", "Yousra", "Karim", "Nadia", "Bilal", "Mima"],
    "grade": ["A", "B", "A", "C", "B", "A", "C", "B", "A"],
    "score": [92, 78, 65, 55, 88, 95, 40, 60, 67]
})

## 1. Combining conditions with `&`, `|`, `~`

In plain Python you'd write `and` / `or`, but pandas needs `&` / `|` / `~` instead — **and each condition needs its own parentheses**.

Why the parentheses are required: Python's operator precedence would otherwise try to evaluate `&` before `>=`, breaking the expression. So writing it without parentheses will error or misbehave — always wrap each condition.

In [13]:
# AND: score >= 60 AND grade == "A"
df[(df["score"] >= 60) & (df["grade"] == "A")]

    name grade  score
0    Ali     A     92
2   Omar     A     65
5  Karim     A     95
8   Mima     A     67

In [14]:
# OR: grade == "A" OR grade == "B"
df[(df["grade"] == "A") | (df["grade"] == "B")]

     name grade  score
0     Ali     A     92
1    Sara     B     78
2    Omar     A     65
4  Yousra     B     88
5   Karim     A     95
7   Bilal     B     60
8    Mima     A     67

In [15]:
# NOT: students NOT in grade "A" 
df[~(df["grade"] == "A")]

     name grade  score
1    Sara     B     78
3    Lina     C     55
4  Yousra     B     88
6   Nadia     C     40
7   Bilal     B     60

## 2. Sorting with `.sort_values()`

In [16]:
# Ascending (default)
df.sort_values("score")

     name grade  score
6   Nadia     C     40
3    Lina     C     55
7   Bilal     B     60
2    Omar     A     65
8    Mima     A     67
1    Sara     B     78
4  Yousra     B     88
0     Ali     A     92
5   Karim     A     95

In [17]:
# Descending
df.sort_values("score", ascending=False)

     name grade  score
5   Karim     A     95
0     Ali     A     92
4  Yousra     B     88
1    Sara     B     78
8    Mima     A     67
2    Omar     A     65
7   Bilal     B     60
3    Lina     C     55
6   Nadia     C     40

In [18]:
# Sort by grade first, then score within each grade
df.sort_values(["grade", "score"])

     name grade  score
2    Omar     A     65
8    Mima     A     67
0     Ali     A     92
5   Karim     A     95
7   Bilal     B     60
1    Sara     B     78
4  Yousra     B     88
6   Nadia     C     40
3    Lina     C     55

## Combining filter + sort in one line

In [19]:
# Filter passing students, then show highest-to-lowest
df[df["score"] >= 60].sort_values("score", ascending=False)

     name grade  score
5   Karim     A     95
0     Ali     A     92
4  Yousra     B     88
1    Sara     B     78
8    Mima     A     67
2    Omar     A     65
7   Bilal     B     60

## Quick review: Day 3 concepts

A few quick variations of what you already learned, just to keep them fresh.

In [20]:
# Review: numpy dtype vs python int
print(type(df["score"].max()))
print(type(int(df["score"].max())))

<class 'numpy.int64'>
<class 'int'>

In [21]:
# Review: groupby + size vs mean
print(df.groupby("grade").size())
print(df.groupby("grade")["score"].mean())

grade
A    4
B    3
C    2
dtype: int64
grade
A    79.750000
B    75.333333
C    47.500000
Name: score, dtype: float64

## Practice Exercises

Write your own functions below. Run each cell to test your code against the sample DataFrame.

**Exercise 1:** Write a function `top_students(df, min_score)` that returns students with `score > min_score`, sorted from highest to lowest score.

In [27]:
def top_students(df, min_score):
    """Return students with score > min_score, sorted highest to lowest."""
    
    return df[df["score"] > min_score].sort_values("score", ascending = False)


    
  
# Test it:
# top_students(df, 60)

In [28]:
top_students(df, 60)

     name grade  score
5   Karim     A     95
0     Ali     A     92
4  Yousra     B     88
1    Sara     B     78
8    Mima     A     67
2    Omar     A     65

**Exercise 2:** Write a function `grade_a_or_b(df)` that returns only students who are in grade "A" **or** grade "B".

In [34]:
def grade_a_or_b(df):
    """Return students in grade A or grade B."""
    return df[(df["grade"] == "A") | (df["grade"] == "B")]
 
    # your code here
    pass

# Test it:

In [35]:
grade_a_or_b(df)

     name grade  score
0     Ali     A     92
1    Sara     B     78
2    Omar     A     65
4  Yousra     B     88
5   Karim     A     95
7   Bilal     B     60
8    Mima     A     67

**Exercise 3:** Write a function `honor_roll(df)` that returns students with `score >= 90` **and** `grade == "A"`, sorted by name alphabetically.

In [36]:
def honor_roll(df):
    """Return students with score >= 90 and grade == 'A', sorted by name."""
    return df[(df["score"] >= 90) & (df["grade"] == "A")].sort_values( by ="name")
    # your code here
    pass

# Test it:
honor_roll(df)

    name grade  score
0    Ali     A     92
5  Karim     A     95