### Filtering using Date Functions

In [18]:
import pandas as pd

In [23]:
df = pd.read_csv(r"C:\Users\seid\Downloads\filtering-using-date-functions-iused.zip")
df

,Formatted Date,Summary,Precip Type,Temperature (C),Apparent Temperature (C),Humidity,Wind Speed (km/h),Wind Bearing (degrees),Visibility (km),Loud Cover,Pressure (millibars),Daily Summary
0,3/26/2006,Mostly Cloudy,rain,5.183333,4.111111,0.91,5.5384,166,9.9820,0,1013.29,Mostly cloudy throughout the day.
1,3/27/2006,Mostly Cloudy,rain,3.722222,2.566667,0.94,5.2003,145,9.9820,0,1013.39,Mostly cloudy throughout the day.
2,3/28/2006,Mostly Cloudy,rain,4.855556,3.705556,0.93,5.6189,170,5.9248,0,1013.45,Mostly cloudy throughout the day.
3,3/29/2006,Foggy,rain,5.211111,5.211111,0.92,4.7656,178,1.2236,0,1013.40,Mostly cloudy throughout the day.
4,3/30/2006,Overcast,rain,6.255556,4.638889,0.92,7.9212,223,7.2128,0,1013.81,Mostly cloudy throughout the day.
...,...,...,...,...,...,...,...,...,...,...,...,...
2358,10/26/2016,Partly Cloudy,snow,-2.155556,-2.155556,0.80,2.7531,176,9.9015,0,1023.52,Partly cloudy until night.
2359,10/27/2016,Partly Cloudy,snow,-2.816667,-2.816667,0.84,3.5098,189,9.8371,0,1024.01,Partly cloudy until night.
2360,10/28/2016,Clear,snow,-2.827778,-4.700000,0.85,4.8461,208,6.1180,0,1023.94,Partly cloudy until night.
2361,10/29/2016,Partly Cloudy,snow,-3.750000,-6.372222,0.91,6.1180,197,6.1180,0,1024.23,Partly cloudy until night.
2362,10/30/2016,Mostly Cloudy,snow,-4.705556,-7.594444,0.91,6.3917,217,6.1180,0,1024.02,Partly cloudy until night.

In [28]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 2363 entries, 0 to 2362
Data columns (total 12 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Formatted Date            2363 non-null   datetime64[us]
 1   Summary                   2363 non-null   str
 2   Precip Type               2363 non-null   str
 3   Temperature (C)           2363 non-null   float64
 4   Apparent Temperature (C)  2363 non-null   float64
 5   Humidity                  2363 non-null   float64
 6   Wind Speed (km/h)         2363 non-null   float64
 7   Wind Bearing (degrees)    2363 non-null   int64
 8   Visibility (km)           2363 non-null   float64
 9   Loud Cover                2363 non-null   int64
 10  Pressure (millibars)      2363 non-null   float64
 11  Daily Summary             2363 non-null   str
dtypes: datetime64[us](1), float64(6), int64(2), str(3)
memory usage: 221.7 KB

In [27]:
df["Formatted Date"] = pd.to_datetime(df["Formatted Date"])

In [24]:
df

,Formatted Date,Summary,Precip Type,Temperature (C),Apparent Temperature (C),Humidity,Wind Speed (km/h),Wind Bearing (degrees),Visibility (km),Loud Cover,Pressure (millibars),Daily Summary
0,3/26/2006,Mostly Cloudy,rain,5.183333,4.111111,0.91,5.5384,166,9.9820,0,1013.29,Mostly cloudy throughout the day.
1,3/27/2006,Mostly Cloudy,rain,3.722222,2.566667,0.94,5.2003,145,9.9820,0,1013.39,Mostly cloudy throughout the day.
2,3/28/2006,Mostly Cloudy,rain,4.855556,3.705556,0.93,5.6189,170,5.9248,0,1013.45,Mostly cloudy throughout the day.
3,3/29/2006,Foggy,rain,5.211111,5.211111,0.92,4.7656,178,1.2236,0,1013.40,Mostly cloudy throughout the day.
4,3/30/2006,Overcast,rain,6.255556,4.638889,0.92,7.9212,223,7.2128,0,1013.81,Mostly cloudy throughout the day.
...,...,...,...,...,...,...,...,...,...,...,...,...
2358,10/26/2016,Partly Cloudy,snow,-2.155556,-2.155556,0.80,2.7531,176,9.9015,0,1023.52,Partly cloudy until night.
2359,10/27/2016,Partly Cloudy,snow,-2.816667,-2.816667,0.84,3.5098,189,9.8371,0,1024.01,Partly cloudy until night.
2360,10/28/2016,Clear,snow,-2.827778,-4.700000,0.85,4.8461,208,6.1180,0,1023.94,Partly cloudy until night.
2361,10/29/2016,Partly Cloudy,snow,-3.750000,-6.372222,0.91,6.1180,197,6.1180,0,1024.23,Partly cloudy until night.
2362,10/30/2016,Mostly Cloudy,snow,-4.705556,-7.594444,0.91,6.3917,217,6.1180,0,1024.02,Partly cloudy until night.

In [37]:
df[df["Formatted Date"].dt.day== 6]

,Formatted Date,Summary,Precip Type,Temperature (C),Apparent Temperature (C),Humidity,Wind Speed (km/h),Wind Bearing (degrees),Visibility (km),Loud Cover,Pressure (millibars),Daily Summary
11,2006-04-06,Mostly Cloudy,rain,11.183333,11.183333,0.80,10.8192,163,14.9569,0,1008.71,Mostly cloudy throughout the day.
41,2006-05-06,Partly Cloudy,rain,16.016667,16.016667,0.48,11.2378,307,11.2700,0,1020.60,Mostly cloudy throughout the day.
72,2006-06-06,Mostly Cloudy,rain,7.338889,5.183333,0.84,11.5437,141,14.1680,0,1011.97,Overcast throughout the day.
102,2006-07-06,Overcast,rain,11.038889,11.038889,0.66,21.4130,311,9.9820,0,1004.30,Foggy overnight and breezy in the morning.
133,2006-08-06,Partly Cloudy,rain,12.755556,12.755556,0.79,13.8299,129,10.8192,0,1005.63,Foggy in the evening.
...,...,...,...,...,...,...,...,...,...,...,...,...
2216,2016-06-06,Foggy,snow,-1.038889,-3.933333,0.99,7.9695,274,1.9159,0,1016.95,Foggy starting overnight continuing until afte...
2246,2016-07-06,Foggy,snow,-2.805556,-6.811111,0.96,10.6099,151,0.1932,0,1009.81,Foggy throughout the day.
2277,2016-08-06,Mostly Cloudy,rain,10.027778,10.027778,0.72,26.5650,158,9.9820,0,1014.40,Partly cloudy until night.
2308,2016-09-06,Foggy,snow,-4.866667,-8.422222,0.92,7.9695,131,0.1610,0,1023.38,Foggy starting overnight continuing until afte...
2338,2016-10-06,Overcast,snow,-3.733333,-3.733333,0.91,3.6225,250,6.0697,0,1023.62,Mostly cloudy until morning.

In [38]:
df[df["Formatted Date"].dt.month== 6]

,Formatted Date,Summary,Precip Type,Temperature (C),Apparent Temperature (C),Humidity,Wind Speed (km/h),Wind Bearing (degrees),Visibility (km),Loud Cover,Pressure (millibars),Daily Summary
67,2006-06-01,Overcast,rain,8.794444,6.816667,0.71,12.3648,20,9.9820,0,1005.89,Foggy overnight and breezy in the morning.
68,2006-06-02,Overcast,rain,6.172222,2.922222,0.76,17.0499,307,9.9820,0,1008.57,Overcast throughout the day.
69,2006-06-03,Overcast,rain,7.983333,6.811111,0.75,7.3416,172,9.9820,0,1010.39,Overcast throughout the day.
70,2006-06-04,Overcast,rain,7.894444,6.127778,0.82,9.9981,142,9.9820,0,1011.32,Overcast throughout the day.
71,2006-06-05,Overcast,rain,7.311111,4.805556,0.83,13.6850,141,11.9784,0,1011.61,Overcast throughout the day.
...,...,...,...,...,...,...,...,...,...,...,...,...
2236,2016-06-26,Foggy,snow,-1.500000,-3.816667,1.00,6.1985,204,0.4025,0,1014.90,Foggy starting overnight continuing until afte...
2237,2016-06-27,Mostly Cloudy,snow,-4.250000,-4.250000,0.93,3.4132,312,8.3237,0,1021.77,Foggy starting overnight continuing until afte...
2238,2016-06-28,Foggy,snow,-0.994444,-0.994444,0.96,3.2522,188,0.7084,0,1015.19,Foggy starting overnight continuing until afte...
2239,2016-06-29,Foggy,snow,-1.594444,-1.594444,0.96,3.1073,184,0.9499,0,1015.02,Foggy starting overnight continuing until afte...
2240,2016-06-30,Foggy,snow,-2.150000,-2.150000,0.96,0.6118,286,0.9499,0,1015.24,Foggy starting overnight continuing until afte...

In [42]:
df[df["Formatted Date"].dt.date == pd.to_datetime("2006/6/3").date()]

,Formatted Date,Summary,Precip Type,Temperature (C),Apparent Temperature (C),Humidity,Wind Speed (km/h),Wind Bearing (degrees),Visibility (km),Loud Cover,Pressure (millibars),Daily Summary
69,2006-06-03,Overcast,rain,7.983333,6.811111,0.75,7.3416,172,9.982,0,1010.39,Overcast throughout the day.

In [41]:
df[df["Formatted Date"].dt.date == pd.to_datetime("2006-06-03").date()]

,Formatted Date,Summary,Precip Type,Temperature (C),Apparent Temperature (C),Humidity,Wind Speed (km/h),Wind Bearing (degrees),Visibility (km),Loud Cover,Pressure (millibars),Daily Summary
69,2006-06-03,Overcast,rain,7.983333,6.811111,0.75,7.3416,172,9.982,0,1010.39,Overcast throughout the day.

In [44]:
df[df["Formatted Date"].dt.day_name() == "Monday"]

,Formatted Date,Summary,Precip Type,Temperature (C),Apparent Temperature (C),Humidity,Wind Speed (km/h),Wind Bearing (degrees),Visibility (km),Loud Cover,Pressure (millibars),Daily Summary
1,2006-03-27,Mostly Cloudy,rain,3.722222,2.566667,0.94,5.2003,145,9.9820,0,1013.39,Mostly cloudy throughout the day.
8,2006-04-03,Partly Cloudy,rain,10.116667,10.116667,0.79,6.6493,163,15.8263,0,1015.40,Partly cloudy throughout the day.
15,2006-04-10,Partly Cloudy,rain,9.355556,7.227778,0.86,14.2646,259,15.8263,0,1015.63,Partly cloudy throughout the day.
22,2006-04-17,Partly Cloudy,rain,10.822222,10.822222,0.82,11.3183,259,9.9820,0,1017.37,Partly cloudy throughout the day.
29,2006-04-24,Partly Cloudy,rain,15.388889,15.388889,0.60,14.4095,251,11.2700,0,1016.15,Partly cloudy throughout the day.
...,...,...,...,...,...,...,...,...,...,...,...,...
2328,2016-09-26,Mostly Cloudy,snow,-2.244444,-2.244444,0.92,3.3488,152,3.9606,0,1024.64,Foggy starting overnight continuing until afte...
2335,2016-10-03,Partly Cloudy,snow,-4.283333,-6.783333,0.91,5.6994,212,6.1663,0,1024.40,Partly cloudy until night.
2342,2016-10-10,Mostly Cloudy,snow,-3.655556,-3.655556,0.87,3.0429,231,6.6493,0,1023.68,Partly cloudy until night.
2349,2016-10-17,Mostly Cloudy,snow,-2.783333,-6.544444,0.85,9.7405,310,9.7566,0,1022.97,Partly cloudy until night.
2356,2016-10-24,Partly Cloudy,rain,0.255556,-2.605556,0.62,8.6135,25,11.4471,0,1022.99,Partly cloudy until night.