### Creating an Index

In [54]:
import pandas as pd

In [55]:
df = pd.read_csv(r"C:\Users\seid\Downloads\creating-an-index-bleua.zip", encoding = "cp1252")
df

    continent       sub_region            country code_3     Unnamed: 4
0        Asia    Southern Asia        Afghanistan    AFG     6,900,000
1      Europe  Northern Europe      Åland Islands    ALA     5,500,000
2      Europe  Southern Europe            Albania    ALB     3,300,000
3      Africa  Northern Africa            Algeria    DZA     9,500,000
4     Oceania        Polynesia     American Samoa    ASM        55,000
..        ...              ...                ...    ...            ...
235   Oceania        Polynesia  Wallis and Futuna    WLF    15,900,000
236    Africa  Northern Africa     Western Sahara    ESH       597,000
237      Asia     Western Asia              Yemen    YEM     5,500,000
238    Africa   Eastern Africa             Zambia    ZMB   213,000,000
239    Africa   Eastern Africa           Zimbabwe    ZWE    19,100,000

[240 rows x 5 columns]

In [56]:
df_world = pd.read_csv(r"C:\Users\seid\Downloads\creating-an-index-bleua.zip", encoding = "cp1252", index_col = "country")
df_world

                  continent       sub_region code_3     Unnamed: 4
country
Afghanistan            Asia    Southern Asia    AFG     6,900,000
Åland Islands        Europe  Northern Europe    ALA     5,500,000
Albania              Europe  Southern Europe    ALB     3,300,000
Algeria              Africa  Northern Africa    DZA     9,500,000
American Samoa      Oceania        Polynesia    ASM        55,000
...                     ...              ...    ...            ...
Wallis and Futuna   Oceania        Polynesia    WLF    15,900,000
Western Sahara       Africa  Northern Africa    ESH       597,000
Yemen                  Asia     Western Asia    YEM     5,500,000
Zambia               Africa   Eastern Africa    ZMB   213,000,000
Zimbabwe             Africa   Eastern Africa    ZWE    19,100,000

[240 rows x 4 columns]

In [57]:
df_continent = pd.read_csv(r"C:\Users\seid\Downloads\creating-an-index-bleua.zip", encoding = "cp1252", index_col = "continent")
df_continent

                sub_region            country code_3     Unnamed: 4
continent
Asia         Southern Asia        Afghanistan    AFG     6,900,000
Europe     Northern Europe      Åland Islands    ALA     5,500,000
Europe     Southern Europe            Albania    ALB     3,300,000
Africa     Northern Africa            Algeria    DZA     9,500,000
Oceania          Polynesia     American Samoa    ASM        55,000
...                    ...                ...    ...            ...
Oceania          Polynesia  Wallis and Futuna    WLF    15,900,000
Africa     Northern Africa     Western Sahara    ESH       597,000
Asia          Western Asia              Yemen    YEM     5,500,000
Africa      Eastern Africa             Zambia    ZMB   213,000,000
Africa      Eastern Africa           Zimbabwe    ZWE    19,100,000

[240 rows x 4 columns]

In [58]:
df_continent.loc['Asia']
df_world.loc['Albania']

continent              Europe
sub_region    Southern Europe
code_3                    ALB
Unnamed: 4         3,300,000
Name: Albania, dtype: object

In [59]:
# put contry as an index
df.set_index('country', inplace = True)
df

                  continent       sub_region code_3     Unnamed: 4
country
Afghanistan            Asia    Southern Asia    AFG     6,900,000
Åland Islands        Europe  Northern Europe    ALA     5,500,000
Albania              Europe  Southern Europe    ALB     3,300,000
Algeria              Africa  Northern Africa    DZA     9,500,000
American Samoa      Oceania        Polynesia    ASM        55,000
...                     ...              ...    ...            ...
Wallis and Futuna   Oceania        Polynesia    WLF    15,900,000
Western Sahara       Africa  Northern Africa    ESH       597,000
Yemen                  Asia     Western Asia    YEM     5,500,000
Zambia               Africa   Eastern Africa    ZMB   213,000,000
Zimbabwe             Africa   Eastern Africa    ZWE    19,100,000

[240 rows x 4 columns]

In [60]:
# remove the index
df.reset_index(inplace = True)
df

               country continent       sub_region code_3     Unnamed: 4
0          Afghanistan      Asia    Southern Asia    AFG     6,900,000
1        Åland Islands    Europe  Northern Europe    ALA     5,500,000
2              Albania    Europe  Southern Europe    ALB     3,300,000
3              Algeria    Africa  Northern Africa    DZA     9,500,000
4       American Samoa   Oceania        Polynesia    ASM        55,000
..                 ...       ...              ...    ...            ...
235  Wallis and Futuna   Oceania        Polynesia    WLF    15,900,000
236     Western Sahara    Africa  Northern Africa    ESH       597,000
237              Yemen      Asia     Western Asia    YEM     5,500,000
238             Zambia    Africa   Eastern Africa    ZMB   213,000,000
239           Zimbabwe    Africa   Eastern Africa    ZWE    19,100,000

[240 rows x 5 columns]