### Reshaping and Pivoting Indexes

In [48]:
import pandas as pd

In [49]:
# Inzip the file first.
import zipfile as zip

with zip.ZipFile (r"C:\Users\seid\Downloads\reshaping-and-pivoting-indexes-pklvl.zip") as z:
    print(z.namelist())

['tech_price.xlsx']

In [50]:
# Unzip and read the Excel file

import zipfile as zip
import pandas as pd

with zip.ZipFile(
    r"C:\Users\seid\Downloads\reshaping-and-pivoting-indexes-pklvl.zip"
) as z:
    
    with z.open("tech_price.xlsx") as f:
        df = pd.read_excel(
            f,
            header=[0, 1],
            index_col=[0, 1]
        )

In [51]:
df

                   USD                 EUR
company           open high low close open high low close
2023-01-01 Apple    89   26  68    69   37   56  11    25
           Google   66   71  26    83   96   68  91    11
           Amazon   12   43  97    75   25   25  90    43
2023-01-02 Apple    54   49  77    49   68   44  85    68
           Google   84   92  55    90   51   50  59    68
           Amazon   41   86  13    19   41   36  50    26
2023-01-03 Apple    67   47  46    70   41   62  72    49
           Google   60   70  54    71   78   47  12    57
           Amazon   71   15  47    53   86   44  68    33
2023-01-04 Apple    56   50  54    83   59   36  45    19
           Google   36   77  27    94   62   13  66    90
           Amazon   64   97  64    56   48   57  45    50
2023-01-05 Apple    34   45  60    84   24   49  63    54
           Google   69   92  14    63   21   85  80    87
           Amazon   63   75  27    43   91   63  95    30

In [52]:
df2 = df.stack()

In [53]:
df2.unstack()

                   USD                 EUR
company           open high low close open high low close
2023-01-01 Amazon   12   43  97    75   25   25  90    43
           Apple    89   26  68    69   37   56  11    25
           Google   66   71  26    83   96   68  91    11
2023-01-02 Amazon   41   86  13    19   41   36  50    26
           Apple    54   49  77    49   68   44  85    68
           Google   84   92  55    90   51   50  59    68
2023-01-03 Amazon   71   15  47    53   86   44  68    33
           Apple    67   47  46    70   41   62  72    49
           Google   60   70  54    71   78   47  12    57
2023-01-04 Amazon   64   97  64    56   48   57  45    50
           Apple    56   50  54    83   59   36  45    19
           Google   36   77  27    94   62   13  66    90
2023-01-05 Amazon   63   75  27    43   91   63  95    30
           Apple    34   45  60    84   24   49  63    54
           Google   69   92  14    63   21   85  80    87

In [54]:
df_world = pd.read_csv(r"C:\Users\seid\Downloads\creating-an-index-bleua.zip", encoding = "cp1252")

pd.set_option('display.max.rows', 1350)
pd.set_option('display.max.columns', 15)
df_world

,continent,sub_region,country,code_3,Unnamed: 4
0,Asia,Southern Asia,Afghanistan,AFG,"6,900,000"
1,Europe,Northern Europe,Åland Islands,ALA,"5,500,000"
2,Europe,Southern Europe,Albania,ALB,"3,300,000"
3,Africa,Northern Africa,Algeria,DZA,"9,500,000"
4,Oceania,Polynesia,American Samoa,ASM,"55,000"
5,Europe,Southern Europe,Andorra,AND,"77,000"
6,Africa,Middle Africa,Angola,AGO,"54,000,000"
7,Americas,Caribbean,Anguilla,AIA,"2,100,000"
8,Americas,Caribbean,Antigua and Barbuda,ATG,"98,000"
9,Americas,South America,Argentina,ARG,"45,000,000"
10,Asia,Western Asia,Armenia,ARM,"45,700,000"
11,Americas,Caribbean,Aruba,ABW,"11,600,000"
12,Oceania,Australia and New Zealand,Australia,AUS,"36,000,000"
13,Europe,Western Europe,Austria,AUT,"9,000,000"
14,Asia,Western Asia,Azerbaijan,AZE,"10,000,000"
15,Americas,Caribbean,Bahamas,BHS,"7,500,000"
16,Asia,Western Asia,Bahrain,BHR,"1,900,000"
17,Asia,Southern Asia,Bangladesh,BGD,"2,500,000"
18,Americas,Caribbean,Barbados,BRB,"44,000,000"
19,Europe,Eastern Europe,Belarus,BLR,"9,400,000"
20,Europe,Western Europe,Belgium,BEL,"12,000,000"
21,Americas,Central America,Belize,BLZ,"9,000,000"
22,Africa,Western Africa,Benin,BEN,"17,400,000"
23,Americas,Northern America,Bermuda,BMU,"64,000"
24,Asia,Southern Asia,Bhutan,BTN,"771,000"
25,Americas,South America,Bolivia (Plurinational State of),BOL,"12,900,000"
26,Americas,Caribbean,"Bonaire, Sint Eustatius and Saba",BES,"4,300,000"
27,Europe,Southern Europe,Bosnia and Herzegovina,BIH,"5,000,000"
28,Africa,Southern Africa,Botswana,BWA,"29,000,000"
29,Americas,South America,Brazil,BRA,"32,700,000"
30,Asia,South-Eastern Asia,Brunei Darussalam,BRN,"9,400,000"
31,Europe,Eastern Europe,Bulgaria,BGR,"6,900,000"
32,Africa,Western Africa,Burkina Faso,BFA,"31,000,000"
33,Africa,Eastern Africa,Burundi,BDI,"128,000,000"
34,Africa,Western Africa,Cabo Verde,CPV,"556,000"
35,Asia,South-Eastern Asia,Cambodia,KHM,"2,200,000"
36,Africa,Middle Africa,Cameroon,CMR,"38,000,000"
37,Americas,Northern America,Canada,CAN,"60,000,000"
38,Americas,Caribbean,Cayman Islands,CYM,"66,000"
39,Africa,Middle Africa,Central African Republic,CAF,"84,000,000"
40,Africa,Middle Africa,Chad,TCD,"2,100,000"
41,Americas,South America,Chile,CHL,"25,000,000"
42,Asia,Eastern Asia,China,CHN,"1,412,000,000"
43,Americas,South America,Colombia,COL,"51,000,000"
44,Africa,Eastern Africa,Comoros,COM,"870,000"
45,Africa,Middle Africa,Congo,COG,"5,500,000"
46,Africa,Middle Africa,Congo (Democratic Republic of the),COD,"89,000,000"
47,Oceania,Polynesia,Cook Islands,COK,"206,000,000"
48,Americas,Central America,Costa Rica,CRI,"5,100,000"
49,Africa,Western Africa,Côte d'Ivoire,CIV,"38,000,000"
50,Europe,Southern Europe,Croatia,HRV,"7,900,000"
51,Americas,Caribbean,Cuba,CUB,"110,000,000"
52,Americas,Caribbean,Curaçao,CUW,"2,600,000"
53,Asia,Western Asia,Cyprus,CYP,"1,200,000"
54,Europe,Eastern Europe,Czech Republic,CZE,"102,000,000"
55,Europe,Northern Europe,Denmark,DNK,"5,800,000"
56,Africa,Eastern Africa,Djibouti,DJI,"988,000"
57,Americas,Caribbean,Dominica,DMA,"72,000"
58,Americas,Caribbean,Dominican Republic,DOM,"11,200,000"
59,Americas,South America,Ecuador,ECU,"2,900,000"
60,Africa,Northern Africa,Egypt,EGY,"11,300,000"
61,Americas,Central America,El Salvador,SLV,"6,500,000"
62,Africa,Middle Africa,Equatorial Guinea,GNQ,"1,700,000"
63,Africa,Eastern Africa,Eritrea,ERI,"5,100,000"
64,Europe,Northern Europe,Estonia,EST,"1,300,000"
65,Africa,Eastern Africa,Ethiopia,ETH,"16,700,000"
66,Americas,South America,Falkland Islands (Malvinas),FLK,"5,500,000"
67,Europe,Northern Europe,Faroe Islands,FRO,"49,000"
68,Oceania,Melanesia,Fiji,FJI,"896,000"
69,Europe,Northern Europe,Finland,FIN,"5,500,000"
70,Europe,Western Europe,France,FRA,"67,000,000"
71,Americas,South America,French Guiana,GUF,"45,000,000"
72,Oceania,Polynesia,French Polynesia,PYF,"40,000,000"
73,Africa,Middle Africa,Gabon,GAB,"28,000,000"
74,Africa,Western Africa,Gambia,GMB,"3,000,000"
75,Asia,Western Asia,Georgia,GEO,"5,400,000"
76,Europe,Western Europe,Germany,DEU,"83,200,000"
77,Africa,Western Africa,Ghana,GHA,"51,000,000"
78,Europe,Southern Europe,Gibraltar,GIB,"6,500,000"
79,Europe,Southern Europe,Greece,GRC,"10,800,000"
80,Americas,Northern America,Greenland,GRL,"56,000"
81,Americas,Caribbean,Grenada,GRD,"16,700,000"
82,Americas,Caribbean,Guadeloupe,GLP,"9,000,000"
83,Oceania,Micronesia,Guam,GUM,"2,800,000"
84,Americas,Central America,Guatemala,GTM,"21,000,000"
85,Europe,Northern Europe,Guernsey,GGY,"63,000"
86,Africa,Western Africa,Guinea,GIN,"18,700,000"
87,Africa,Western Africa,Guinea-Bissau,GNB,"10,000,000"
88,Americas,South America,Guyana,GUY,"787,000"
89,Americas,Caribbean,Haiti,HTI,"114,000,000"
90,Europe,Southern Europe,Holy See,VAT,800
91,Americas,Central America,Honduras,HND,"10,000,000"
92,Asia,Eastern Asia,Hong Kong,HKG,"7,500,000"
93,Europe,Eastern Europe,Hungary,HUN,"9,600,000"
94,Europe,Northern Europe,Iceland,ISL,"6,900,000"
95,Asia,Southern Asia,India,IND,"1,400,000,000"
96,Asia,South-Eastern Asia,Indonesia,IDN,"4,600,000"
97,Asia,Southern Asia,Iran (Islamic Republic of),IRN,"84,000,000"
98,Asia,Western Asia,Iraq,IRQ,"89,000,000"
99,Europe,Northern Europe,Ireland,IRL,"5,000,000"
100,Europe,Northern Europe,Isle of Man,IMN,"85,000"
101,Asia,Western Asia,Israel,ISR,"9,300,000"
102,Europe,Southern Europe,Italy,ITA,"60,000,000"
103,Americas,Caribbean,Jamaica,JAM,"3,700,000"
104,Asia,Eastern Asia,Japan,JPN,"18,000,000"
105,Europe,Northern Europe,Jersey,JEY,"11,800,000"
106,Asia,Western Asia,Jordan,JOR,"10,300,000"
107,Asia,Central Asia,Kazakhstan,KAZ,"22,000,000"
108,Africa,Eastern Africa,Kenya,KEN,"53,800,000"
109,Oceania,Micronesia,Kiribati,KIR,"17,600,000"
110,Asia,Eastern Asia,Korea (Democratic People's Republic of),PRK,"38,000,000"
111,Asia,Eastern Asia,Korea (Republic of),KOR,"51,600,000"
112,Asia,Western Asia,Kuwait,KWT,"8,300,000"
113,Asia,Central Asia,Kyrgyzstan,KGZ,"6,600,000"
114,Asia,South-Eastern Asia,Lao People's Democratic Republic,LAO,"7,300,000"
115,Europe,Northern Europe,Latvia,LVA,"10,000,000"
116,Asia,Western Asia,Lebanon,LBN,"6,800,000"
117,Africa,Southern Africa,Lesotho,LSO,"27,700,000"
118,Africa,Western Africa,Liberia,LBR,"5,000,000"
119,Africa,Northern Africa,Libya,LBY,"6,900,000"
120,Europe,Western Europe,Liechtenstein,LIE,"68,000,000"
121,Europe,Northern Europe,Lithuania,LTU,"3,500,000"
122,Europe,Western Europe,Luxembourg,LUX,"633,000"
123,Asia,Eastern Asia,Macao,MAC,"650,000"
124,Europe,Southern Europe,Macedonia (the former Yugoslav Republic of),MKD,"26,000,000"
125,Africa,Eastern Africa,Madagascar,MDG,"4,300,000"
126,Africa,Eastern Africa,Malawi,MWI,"25,800,000"
127,Asia,South-Eastern Asia,Malaysia,MYS,"53,800,000"
128,Asia,Southern Asia,Maldives,MDV,"540,000"
129,Africa,Western Africa,Mali,MLI,"30,000,000"
130,Europe,Southern Europe,Malta,MLT,"97,000,000"
131,Oceania,Micronesia,Marshall Islands,MHL,"59,000"
132,Americas,Caribbean,Martinique,MTQ,"6,900,000"
133,Africa,Western Africa,Mauritania,MRT,"83,200,000"
134,Africa,Eastern Africa,Mauritius,MUS,"1,300,000"
135,Africa,Eastern Africa,Mayotte,MYT,"4,800,000"
136,Americas,Central America,Mexico,MEX,"18,400,000"
137,Oceania,Micronesia,Micronesia (Federated States of),FSM,"164,000,000"
138,Europe,Eastern Europe,Moldova (Republic of),MDA,"3,300,000"
139,Europe,Western Europe,Monaco,MCO,"7,100,000"
140,Asia,Eastern Asia,Mongolia,MNG,"5,000,000"
141,Europe,Southern Europe,Montenegro,MNE,"622,000"
142,Americas,Caribbean,Montserrat,MSR,"5,000"
143,Africa,Northern Africa,Morocco,MAR,"6,800,000"
144,Africa,Eastern Africa,Mozambique,MOZ,"51,600,000"
145,Asia,South-Eastern Asia,Myanmar,MMR,"54,000,000"
146,Africa,Southern Africa,Namibia,NAM,"3,200,000"
147,Oceania,Micronesia,Nauru,NRU,"144,000,000"
148,Asia,Southern Asia,Nepal,NPL,"44,000,000"
149,Europe,Western Europe,Netherlands,NLD,"2,800,000"
150,Oceania,Melanesia,New Caledonia,NCL,"44,000,000"
151,Oceania,Australia and New Zealand,New Zealand,NZL,"84,000,000"
152,Americas,Central America,Nicaragua,NIC,"6,600,000"
153,Africa,Western Africa,Niger,NER,"35,000,000"
154,Africa,Western Africa,Nigeria,NGA,"31,000,000"
155,Oceania,Polynesia,Niue,NIU,"2,400,000"
156,Oceania,Australia and New Zealand,Norfolk Island,NFK,"20,300,000"
157,Oceania,Micronesia,Northern Mariana Islands,MNP,"58,000"
158,Europe,Northern Europe,Norway,NOR,"5,400,000"
159,Asia,Western Asia,Oman,OMN,"5,000,000"
160,Asia,Southern Asia,Pakistan,PAK,"331,000,000"
161,Oceania,Micronesia,Palau,PLW,"220,000,000"
162,Asia,Western Asia,"Palestine, State of",PSE,"5,100,000"
163,Americas,Central America,Panama,PAN,"8,700,000"
164,Oceania,Melanesia,Papua New Guinea,PNG,"9,000,000"
165,Americas,South America,Paraguay,PRY,"7,100,000"
166,Americas,South America,Peru,PER,"59,000,000"
167,Asia,South-Eastern Asia,Philippines,PHL,"13,100,000"
168,Oceania,Polynesia,Pitcairn,PCN,"50,000,000"
169,Europe,Eastern Europe,Poland,POL,"67,000,000"
170,Europe,Southern Europe,Portugal,PRT,"10,400,000"
171,Americas,Caribbean,Puerto Rico,PRI,"47,000,000"
172,Asia,Western Asia,Qatar,QAT,"3,500,000"
173,Africa,Eastern Africa,Réunion,REU,"859,000"
174,Europe,Eastern Europe,Romania,ROU,"24,000,000"
175,Europe,Eastern Europe,Russian Federation,RUS,"19,000,000"
176,Africa,Eastern Africa,Rwanda,RWA,"17,500,000"
177,Americas,Caribbean,Saint Barthélemy,BLM,"9,900"
178,Africa,Western Africa,"Saint Helena, Ascension and Tristan da Cunha",SHN,"6,000"
179,Americas,Caribbean,Saint Kitts and Nevis,KNA,"53,000"
180,Americas,Caribbean,Saint Lucia,LCA,"23,800,000"
181,Americas,Caribbean,Saint Martin (French part),MAF,"7,300,000"
182,Americas,Northern America,Saint Pierre and Miquelon,SPM,"5,700"
183,Americas,Caribbean,Saint Vincent and the Grenadines,VCT,"16,400,000"
184,Oceania,Polynesia,Samoa,WSM,"26,000,000"
185,Europe,Southern Europe,San Marino,SMR,"6,600,000"
186,Africa,Middle Africa,Sao Tome and Principe,STP,"33,000,000"
187,Asia,Western Asia,Saudi Arabia,SAU,"6,600,000"
188,Africa,Western Africa,Senegal,SEN,"2,300,000"
189,Europe,Southern Europe,Serbia,SRB,"6,900,000"
190,Africa,Eastern Africa,Seychelles,SYC,"98,000"
191,Africa,Western Africa,Sierra Leone,SLE,"7,900,000"
192,Asia,South-Eastern Asia,Singapore,SGP,"5,900,000"
193,Americas,Caribbean,Sint Maarten (Dutch part),SXM,"9,300,000"
194,Europe,Eastern Europe,Slovakia,SVK,"5,500,000"
195,Europe,Southern Europe,Slovenia,SVN,"276,000,000"
196,Oceania,Melanesia,Solomon Islands,SLB,"686,000"
197,Africa,Eastern Africa,Somalia,SOM,"19,100,000"
198,Africa,Southern Africa,South Africa,ZAF,"59,000,000"
199,Africa,Eastern Africa,South Sudan,SSD,"11,900,000"
200,Europe,Southern Europe,Spain,ESP,"47,000,000"
201,Asia,Southern Asia,Sri Lanka,LKA,"33,000,000"
202,Africa,Northern Africa,Sudan,SDN,"9,600,000"
203,Americas,South America,Suriname,SUR,"591,000"
204,Europe,Northern Europe,Svalbard and Jan Mayen,SJM,"4,000,000"
205,Africa,Southern Africa,Swaziland,SWZ,"1,200,000"
206,Europe,Northern Europe,Sweden,SWE,"10,700,000"
207,Europe,Western Europe,Switzerland,CHE,"8,700,000"
208,Asia,Western Asia,Syrian Arab Republic,SYR,"2,800,000"
209,Asia,Eastern Asia,"Taiwan, Province of China",TWN,"34,000,000"
210,Asia,Central Asia,Tajikistan,TJK,"9,500,000"
211,Africa,Eastern Africa,"Tanzania, United Republic of",TZA,"59,700,000"
212,Asia,South-Eastern Asia,Thailand,THA,"69,800,000"
213,Asia,South-Eastern Asia,Timor-Leste,TLS,"1,300,000"
214,Africa,Western Africa,Togo,TGO,"8,300,000"
215,Oceania,Polynesia,Tokelau,TKL,"2,000,000"
216,Oceania,Polynesia,Tonga,TON,"11,500,000"
217,Americas,Caribbean,Trinidad and Tobago,TTO,"1,900,000"
218,Africa,Northern Africa,Tunisia,TUN,"125,000,000"
219,Asia,Western Asia,Turkey,TUR,"84,000,000"
220,Asia,Central Asia,Turkmenistan,TKM,"6,000,000"
221,Americas,Caribbean,Turks and Caicos Islands,TCA,"69,800,000"
222,Oceania,Polynesia,Tuvalu,TUV,"15,000,000"
223,Africa,Eastern Africa,Uganda,UGA,"45,700,000"
224,Europe,Eastern Europe,Ukraine,UKR,"9,900,000"
225,Asia,Western Asia,United Arab Emirates,ARE,"9,900,000"
226,Europe,Northern Europe,United Kingdom of Great Britain and Northern I...,GBR,"68,000,000"
227,Americas,Northern America,United States of America,USA,"59,700,000"
228,Americas,South America,Uruguay,URY,"5,100,000"
229,Asia,Central Asia,Uzbekistan,UZB,"6,000,000"
230,Oceania,Melanesia,Vanuatu,VUT,"5,900,000"
231,Americas,South America,Venezuela (Bolivarian Republic of),VEN,"4,900,000"
232,Asia,South-Eastern Asia,Viet Nam,VNM,"97,000,000"
233,Americas,Caribbean,Virgin Islands (British),VGB,"5,800,000"
234,Americas,Caribbean,Virgin Islands (U.S.),VIR,"11,400,000"
235,Oceania,Polynesia,Wallis and Futuna,WLF,"15,900,000"
236,Africa,Northern Africa,Western Sahara,ESH,"597,000"
237,Asia,Western Asia,Yemen,YEM,"5,500,000"
238,Africa,Eastern Africa,Zambia,ZMB,"213,000,000"
239,Africa,Eastern Africa,Zimbabwe,ZWE,"19,100,000"

In [55]:
df_world.pivot(index = ['continent', 'sub_region'], columns = 'country', values = 'Unnamed: 4')

country                              Afghanistan      Albania      Algeria  \
continent sub_region
Africa    Eastern Africa                     NaN          NaN          NaN
          Middle Africa                      NaN          NaN          NaN
          Northern Africa                    NaN          NaN   9,500,000
          Southern Africa                    NaN          NaN          NaN
          Western Africa                     NaN          NaN          NaN
Americas  Caribbean                          NaN          NaN          NaN
          Central America                    NaN          NaN          NaN
          Northern America                   NaN          NaN          NaN
          South America                      NaN          NaN          NaN
Asia      Central Asia                       NaN          NaN          NaN
          Eastern Asia                       NaN          NaN          NaN
          South-Eastern Asia                 NaN          NaN          NaN
          Southern Asia               6,900,000           NaN          NaN
          Western Asia                       NaN          NaN          NaN
Europe    Eastern Europe                     NaN          NaN          NaN
          Northern Europe                    NaN          NaN          NaN
          Southern Europe                    NaN   3,300,000           NaN
          Western Europe                     NaN          NaN          NaN
Oceania   Australia and New Zealand          NaN          NaN          NaN
          Melanesia                          NaN          NaN          NaN
          Micronesia                         NaN          NaN          NaN
          Polynesia                          NaN          NaN          NaN

country                             American Samoa   Andorra        Angola  \
continent sub_region
Africa    Eastern Africa                       NaN       NaN           NaN
          Middle Africa                        NaN       NaN   54,000,000
          Northern Africa                      NaN       NaN           NaN
          Southern Africa                      NaN       NaN           NaN
          Western Africa                       NaN       NaN           NaN
Americas  Caribbean                            NaN       NaN           NaN
          Central America                      NaN       NaN           NaN
          Northern America                     NaN       NaN           NaN
          South America                        NaN       NaN           NaN
Asia      Central Asia                         NaN       NaN           NaN
          Eastern Asia                         NaN       NaN           NaN
          South-Eastern Asia                   NaN       NaN           NaN
          Southern Asia                        NaN       NaN           NaN
          Western Asia                         NaN       NaN           NaN
Europe    Eastern Europe                       NaN       NaN           NaN
          Northern Europe                      NaN       NaN           NaN
          Southern Europe                      NaN   77,000            NaN
          Western Europe                       NaN       NaN           NaN
Oceania   Australia and New Zealand            NaN       NaN           NaN
          Melanesia                            NaN       NaN           NaN
          Micronesia                           NaN       NaN           NaN
          Polynesia                        55,000        NaN           NaN

country                                 Anguilla  ... Virgin Islands (U.S.)  \
continent sub_region                              ...
Africa    Eastern Africa                     NaN  ...                   NaN
          Middle Africa                      NaN  ...                   NaN
          Northern Africa                    NaN  ...                   NaN
          Southern Africa                    NaN  ...                   NaN
          Western Africa                     NaN  ...                   NaN
Americas  Caribbean                   2,100,000   ...           11,400,000
          Central America                    NaN  ...                   NaN
          Northern America                   NaN  ...                   NaN
          South America                      NaN  ...                   NaN
Asia      Central Asia                       NaN  ...                   NaN
          Eastern Asia                       NaN  ...                   NaN
          South-Eastern Asia                 NaN  ...                   NaN
          Southern Asia                      NaN  ...                   NaN
          Western Asia                       NaN  ...                   NaN
Europe    Eastern Europe                     NaN  ...                   NaN
          Northern Europe                    NaN  ...                   NaN
          Southern Europe                    NaN  ...                   NaN
          Western Europe                     NaN  ...                   NaN
Oceania   Australia and New Zealand          NaN  ...                   NaN
          Melanesia                          NaN  ...                   NaN
          Micronesia                         NaN  ...                   NaN
          Polynesia                          NaN  ...                   NaN

country                             Wallis and Futuna Western Sahara  \
continent sub_region
Africa    Eastern Africa                          NaN            NaN
          Middle Africa                           NaN            NaN
          Northern Africa                         NaN       597,000
          Southern Africa                         NaN            NaN
          Western Africa                          NaN            NaN
Americas  Caribbean                               NaN            NaN
          Central America                         NaN            NaN
          Northern America                        NaN            NaN
          South America                           NaN            NaN
Asia      Central Asia                            NaN            NaN
          Eastern Asia                            NaN            NaN
          South-Eastern Asia                      NaN            NaN
          Southern Asia                           NaN            NaN
          Western Asia                            NaN            NaN
Europe    Eastern Europe                          NaN            NaN
          Northern Europe                         NaN            NaN
          Southern Europe                         NaN            NaN
          Western Europe                          NaN            NaN
Oceania   Australia and New Zealand               NaN            NaN
          Melanesia                               NaN            NaN
          Micronesia                              NaN            NaN
          Polynesia                       15,900,000             NaN

country                                    Yemen         Zambia      Zimbabwe  \
continent sub_region
Africa    Eastern Africa                     NaN   213,000,000    19,100,000
          Middle Africa                      NaN            NaN           NaN
          Northern Africa                    NaN            NaN           NaN
          Southern Africa                    NaN            NaN           NaN
          Western Africa                     NaN            NaN           NaN
Americas  Caribbean                          NaN            NaN           NaN
          Central America                    NaN            NaN           NaN
          Northern America                   NaN            NaN           NaN
          South America                      NaN            NaN           NaN
Asia      Central Asia                       NaN            NaN           NaN
          Eastern Asia                       NaN            NaN           NaN
          South-Eastern Asia                 NaN            NaN           NaN
          Southern Asia                      NaN            NaN           NaN
          Western Asia                5,500,000             NaN           NaN
Europe    Eastern Europe                     NaN            NaN           NaN
          Northern Europe                    NaN            NaN           NaN
          Southern Europe                    NaN            NaN           NaN
          Western Europe                     NaN            NaN           NaN
Oceania   Australia and New Zealand          NaN            NaN           NaN
          Melanesia                          NaN            NaN           NaN
          Micronesia                         NaN            NaN           NaN
          Polynesia                          NaN            NaN           NaN

country                             Åland Islands
continent sub_region
Africa    Eastern Africa                      NaN
          Middle Africa                       NaN
          Northern Africa                     NaN
          Southern Africa                     NaN
          Western Africa                      NaN
Americas  Caribbean                           NaN
          Central America                     NaN
          Northern America                    NaN
          South America                       NaN
Asia      Central Asia                        NaN
          Eastern Asia                        NaN
          South-Eastern Asia                  NaN
          Southern Asia                       NaN
          Western Asia                        NaN
Europe    Eastern Europe                      NaN
          Northern Europe              5,500,000
          Southern Europe                     NaN
          Western Europe                      NaN
Oceania   Australia and New Zealand           NaN
          Melanesia                           NaN
          Micronesia                          NaN
          Polynesia                           NaN

[22 rows x 240 columns]

In [59]:
df_world.rename(columns = {"Unnamed: 4": "Population"}, inplace = True)

In [61]:
df_world.pivot(index = ['continent', 'sub_region'], columns = 'country', values = 'Population')

country                              Afghanistan      Albania      Algeria  \
continent sub_region
Africa    Eastern Africa                     NaN          NaN          NaN
          Middle Africa                      NaN          NaN          NaN
          Northern Africa                    NaN          NaN   9,500,000
          Southern Africa                    NaN          NaN          NaN
          Western Africa                     NaN          NaN          NaN
Americas  Caribbean                          NaN          NaN          NaN
          Central America                    NaN          NaN          NaN
          Northern America                   NaN          NaN          NaN
          South America                      NaN          NaN          NaN
Asia      Central Asia                       NaN          NaN          NaN
          Eastern Asia                       NaN          NaN          NaN
          South-Eastern Asia                 NaN          NaN          NaN
          Southern Asia               6,900,000           NaN          NaN
          Western Asia                       NaN          NaN          NaN
Europe    Eastern Europe                     NaN          NaN          NaN
          Northern Europe                    NaN          NaN          NaN
          Southern Europe                    NaN   3,300,000           NaN
          Western Europe                     NaN          NaN          NaN
Oceania   Australia and New Zealand          NaN          NaN          NaN
          Melanesia                          NaN          NaN          NaN
          Micronesia                         NaN          NaN          NaN
          Polynesia                          NaN          NaN          NaN

country                             American Samoa   Andorra        Angola  \
continent sub_region
Africa    Eastern Africa                       NaN       NaN           NaN
          Middle Africa                        NaN       NaN   54,000,000
          Northern Africa                      NaN       NaN           NaN
          Southern Africa                      NaN       NaN           NaN
          Western Africa                       NaN       NaN           NaN
Americas  Caribbean                            NaN       NaN           NaN
          Central America                      NaN       NaN           NaN
          Northern America                     NaN       NaN           NaN
          South America                        NaN       NaN           NaN
Asia      Central Asia                         NaN       NaN           NaN
          Eastern Asia                         NaN       NaN           NaN
          South-Eastern Asia                   NaN       NaN           NaN
          Southern Asia                        NaN       NaN           NaN
          Western Asia                         NaN       NaN           NaN
Europe    Eastern Europe                       NaN       NaN           NaN
          Northern Europe                      NaN       NaN           NaN
          Southern Europe                      NaN   77,000            NaN
          Western Europe                       NaN       NaN           NaN
Oceania   Australia and New Zealand            NaN       NaN           NaN
          Melanesia                            NaN       NaN           NaN
          Micronesia                           NaN       NaN           NaN
          Polynesia                        55,000        NaN           NaN

country                                 Anguilla  ... Virgin Islands (U.S.)  \
continent sub_region                              ...
Africa    Eastern Africa                     NaN  ...                   NaN
          Middle Africa                      NaN  ...                   NaN
          Northern Africa                    NaN  ...                   NaN
          Southern Africa                    NaN  ...                   NaN
          Western Africa                     NaN  ...                   NaN
Americas  Caribbean                   2,100,000   ...           11,400,000
          Central America                    NaN  ...                   NaN
          Northern America                   NaN  ...                   NaN
          South America                      NaN  ...                   NaN
Asia      Central Asia                       NaN  ...                   NaN
          Eastern Asia                       NaN  ...                   NaN
          South-Eastern Asia                 NaN  ...                   NaN
          Southern Asia                      NaN  ...                   NaN
          Western Asia                       NaN  ...                   NaN
Europe    Eastern Europe                     NaN  ...                   NaN
          Northern Europe                    NaN  ...                   NaN
          Southern Europe                    NaN  ...                   NaN
          Western Europe                     NaN  ...                   NaN
Oceania   Australia and New Zealand          NaN  ...                   NaN
          Melanesia                          NaN  ...                   NaN
          Micronesia                         NaN  ...                   NaN
          Polynesia                          NaN  ...                   NaN

country                             Wallis and Futuna Western Sahara  \
continent sub_region
Africa    Eastern Africa                          NaN            NaN
          Middle Africa                           NaN            NaN
          Northern Africa                         NaN       597,000
          Southern Africa                         NaN            NaN
          Western Africa                          NaN            NaN
Americas  Caribbean                               NaN            NaN
          Central America                         NaN            NaN
          Northern America                        NaN            NaN
          South America                           NaN            NaN
Asia      Central Asia                            NaN            NaN
          Eastern Asia                            NaN            NaN
          South-Eastern Asia                      NaN            NaN
          Southern Asia                           NaN            NaN
          Western Asia                            NaN            NaN
Europe    Eastern Europe                          NaN            NaN
          Northern Europe                         NaN            NaN
          Southern Europe                         NaN            NaN
          Western Europe                          NaN            NaN
Oceania   Australia and New Zealand               NaN            NaN
          Melanesia                               NaN            NaN
          Micronesia                              NaN            NaN
          Polynesia                       15,900,000             NaN

country                                    Yemen         Zambia      Zimbabwe  \
continent sub_region
Africa    Eastern Africa                     NaN   213,000,000    19,100,000
          Middle Africa                      NaN            NaN           NaN
          Northern Africa                    NaN            NaN           NaN
          Southern Africa                    NaN            NaN           NaN
          Western Africa                     NaN            NaN           NaN
Americas  Caribbean                          NaN            NaN           NaN
          Central America                    NaN            NaN           NaN
          Northern America                   NaN            NaN           NaN
          South America                      NaN            NaN           NaN
Asia      Central Asia                       NaN            NaN           NaN
          Eastern Asia                       NaN            NaN           NaN
          South-Eastern Asia                 NaN            NaN           NaN
          Southern Asia                      NaN            NaN           NaN
          Western Asia                5,500,000             NaN           NaN
Europe    Eastern Europe                     NaN            NaN           NaN
          Northern Europe                    NaN            NaN           NaN
          Southern Europe                    NaN            NaN           NaN
          Western Europe                     NaN            NaN           NaN
Oceania   Australia and New Zealand          NaN            NaN           NaN
          Melanesia                          NaN            NaN           NaN
          Micronesia                         NaN            NaN           NaN
          Polynesia                          NaN            NaN           NaN

country                             Åland Islands
continent sub_region
Africa    Eastern Africa                      NaN
          Middle Africa                       NaN
          Northern Africa                     NaN
          Southern Africa                     NaN
          Western Africa                      NaN
Americas  Caribbean                           NaN
          Central America                     NaN
          Northern America                    NaN
          South America                       NaN
Asia      Central Asia                        NaN
          Eastern Asia                        NaN
          South-Eastern Asia                  NaN
          Southern Asia                       NaN
          Western Asia                        NaN
Europe    Eastern Europe                      NaN
          Northern Europe              5,500,000
          Southern Europe                     NaN
          Western Europe                      NaN
Oceania   Australia and New Zealand           NaN
          Melanesia                           NaN
          Micronesia                          NaN
          Polynesia                           NaN

[22 rows x 240 columns]