### Multi-Level Indexing

In [46]:
import pandas as pd

In [47]:
df = pd.read_csv(r"C:\Users\seid\Downloads\creating-an-index-bleua.zip", encoding = "cp1252")

pd.set_option('display.max.rows', 1350)
pd.set_option('display.max.columns', 15)
df

,continent,sub_region,country,code_3,Unnamed: 4
0,Asia,Southern Asia,Afghanistan,AFG,"6,900,000"
1,Europe,Northern Europe,Åland Islands,ALA,"5,500,000"
2,Europe,Southern Europe,Albania,ALB,"3,300,000"
3,Africa,Northern Africa,Algeria,DZA,"9,500,000"
4,Oceania,Polynesia,American Samoa,ASM,"55,000"
5,Europe,Southern Europe,Andorra,AND,"77,000"
6,Africa,Middle Africa,Angola,AGO,"54,000,000"
7,Americas,Caribbean,Anguilla,AIA,"2,100,000"
8,Americas,Caribbean,Antigua and Barbuda,ATG,"98,000"
9,Americas,South America,Argentina,ARG,"45,000,000"
10,Asia,Western Asia,Armenia,ARM,"45,700,000"
11,Americas,Caribbean,Aruba,ABW,"11,600,000"
12,Oceania,Australia and New Zealand,Australia,AUS,"36,000,000"
13,Europe,Western Europe,Austria,AUT,"9,000,000"
14,Asia,Western Asia,Azerbaijan,AZE,"10,000,000"
15,Americas,Caribbean,Bahamas,BHS,"7,500,000"
16,Asia,Western Asia,Bahrain,BHR,"1,900,000"
17,Asia,Southern Asia,Bangladesh,BGD,"2,500,000"
18,Americas,Caribbean,Barbados,BRB,"44,000,000"
19,Europe,Eastern Europe,Belarus,BLR,"9,400,000"
20,Europe,Western Europe,Belgium,BEL,"12,000,000"
21,Americas,Central America,Belize,BLZ,"9,000,000"
22,Africa,Western Africa,Benin,BEN,"17,400,000"
23,Americas,Northern America,Bermuda,BMU,"64,000"
24,Asia,Southern Asia,Bhutan,BTN,"771,000"
25,Americas,South America,Bolivia (Plurinational State of),BOL,"12,900,000"
26,Americas,Caribbean,"Bonaire, Sint Eustatius and Saba",BES,"4,300,000"
27,Europe,Southern Europe,Bosnia and Herzegovina,BIH,"5,000,000"
28,Africa,Southern Africa,Botswana,BWA,"29,000,000"
29,Americas,South America,Brazil,BRA,"32,700,000"
30,Asia,South-Eastern Asia,Brunei Darussalam,BRN,"9,400,000"
31,Europe,Eastern Europe,Bulgaria,BGR,"6,900,000"
32,Africa,Western Africa,Burkina Faso,BFA,"31,000,000"
33,Africa,Eastern Africa,Burundi,BDI,"128,000,000"
34,Africa,Western Africa,Cabo Verde,CPV,"556,000"
35,Asia,South-Eastern Asia,Cambodia,KHM,"2,200,000"
36,Africa,Middle Africa,Cameroon,CMR,"38,000,000"
37,Americas,Northern America,Canada,CAN,"60,000,000"
38,Americas,Caribbean,Cayman Islands,CYM,"66,000"
39,Africa,Middle Africa,Central African Republic,CAF,"84,000,000"
40,Africa,Middle Africa,Chad,TCD,"2,100,000"
41,Americas,South America,Chile,CHL,"25,000,000"
42,Asia,Eastern Asia,China,CHN,"1,412,000,000"
43,Americas,South America,Colombia,COL,"51,000,000"
44,Africa,Eastern Africa,Comoros,COM,"870,000"
45,Africa,Middle Africa,Congo,COG,"5,500,000"
46,Africa,Middle Africa,Congo (Democratic Republic of the),COD,"89,000,000"
47,Oceania,Polynesia,Cook Islands,COK,"206,000,000"
48,Americas,Central America,Costa Rica,CRI,"5,100,000"
49,Africa,Western Africa,Côte d'Ivoire,CIV,"38,000,000"
50,Europe,Southern Europe,Croatia,HRV,"7,900,000"
51,Americas,Caribbean,Cuba,CUB,"110,000,000"
52,Americas,Caribbean,Curaçao,CUW,"2,600,000"
53,Asia,Western Asia,Cyprus,CYP,"1,200,000"
54,Europe,Eastern Europe,Czech Republic,CZE,"102,000,000"
55,Europe,Northern Europe,Denmark,DNK,"5,800,000"
56,Africa,Eastern Africa,Djibouti,DJI,"988,000"
57,Americas,Caribbean,Dominica,DMA,"72,000"
58,Americas,Caribbean,Dominican Republic,DOM,"11,200,000"
59,Americas,South America,Ecuador,ECU,"2,900,000"
60,Africa,Northern Africa,Egypt,EGY,"11,300,000"
61,Americas,Central America,El Salvador,SLV,"6,500,000"
62,Africa,Middle Africa,Equatorial Guinea,GNQ,"1,700,000"
63,Africa,Eastern Africa,Eritrea,ERI,"5,100,000"
64,Europe,Northern Europe,Estonia,EST,"1,300,000"
65,Africa,Eastern Africa,Ethiopia,ETH,"16,700,000"
66,Americas,South America,Falkland Islands (Malvinas),FLK,"5,500,000"
67,Europe,Northern Europe,Faroe Islands,FRO,"49,000"
68,Oceania,Melanesia,Fiji,FJI,"896,000"
69,Europe,Northern Europe,Finland,FIN,"5,500,000"
70,Europe,Western Europe,France,FRA,"67,000,000"
71,Americas,South America,French Guiana,GUF,"45,000,000"
72,Oceania,Polynesia,French Polynesia,PYF,"40,000,000"
73,Africa,Middle Africa,Gabon,GAB,"28,000,000"
74,Africa,Western Africa,Gambia,GMB,"3,000,000"
75,Asia,Western Asia,Georgia,GEO,"5,400,000"
76,Europe,Western Europe,Germany,DEU,"83,200,000"
77,Africa,Western Africa,Ghana,GHA,"51,000,000"
78,Europe,Southern Europe,Gibraltar,GIB,"6,500,000"
79,Europe,Southern Europe,Greece,GRC,"10,800,000"
80,Americas,Northern America,Greenland,GRL,"56,000"
81,Americas,Caribbean,Grenada,GRD,"16,700,000"
82,Americas,Caribbean,Guadeloupe,GLP,"9,000,000"
83,Oceania,Micronesia,Guam,GUM,"2,800,000"
84,Americas,Central America,Guatemala,GTM,"21,000,000"
85,Europe,Northern Europe,Guernsey,GGY,"63,000"
86,Africa,Western Africa,Guinea,GIN,"18,700,000"
87,Africa,Western Africa,Guinea-Bissau,GNB,"10,000,000"
88,Americas,South America,Guyana,GUY,"787,000"
89,Americas,Caribbean,Haiti,HTI,"114,000,000"
90,Europe,Southern Europe,Holy See,VAT,800
91,Americas,Central America,Honduras,HND,"10,000,000"
92,Asia,Eastern Asia,Hong Kong,HKG,"7,500,000"
93,Europe,Eastern Europe,Hungary,HUN,"9,600,000"
94,Europe,Northern Europe,Iceland,ISL,"6,900,000"
95,Asia,Southern Asia,India,IND,"1,400,000,000"
96,Asia,South-Eastern Asia,Indonesia,IDN,"4,600,000"
97,Asia,Southern Asia,Iran (Islamic Republic of),IRN,"84,000,000"
98,Asia,Western Asia,Iraq,IRQ,"89,000,000"
99,Europe,Northern Europe,Ireland,IRL,"5,000,000"
100,Europe,Northern Europe,Isle of Man,IMN,"85,000"
101,Asia,Western Asia,Israel,ISR,"9,300,000"
102,Europe,Southern Europe,Italy,ITA,"60,000,000"
103,Americas,Caribbean,Jamaica,JAM,"3,700,000"
104,Asia,Eastern Asia,Japan,JPN,"18,000,000"
105,Europe,Northern Europe,Jersey,JEY,"11,800,000"
106,Asia,Western Asia,Jordan,JOR,"10,300,000"
107,Asia,Central Asia,Kazakhstan,KAZ,"22,000,000"
108,Africa,Eastern Africa,Kenya,KEN,"53,800,000"
109,Oceania,Micronesia,Kiribati,KIR,"17,600,000"
110,Asia,Eastern Asia,Korea (Democratic People's Republic of),PRK,"38,000,000"
111,Asia,Eastern Asia,Korea (Republic of),KOR,"51,600,000"
112,Asia,Western Asia,Kuwait,KWT,"8,300,000"
113,Asia,Central Asia,Kyrgyzstan,KGZ,"6,600,000"
114,Asia,South-Eastern Asia,Lao People's Democratic Republic,LAO,"7,300,000"
115,Europe,Northern Europe,Latvia,LVA,"10,000,000"
116,Asia,Western Asia,Lebanon,LBN,"6,800,000"
117,Africa,Southern Africa,Lesotho,LSO,"27,700,000"
118,Africa,Western Africa,Liberia,LBR,"5,000,000"
119,Africa,Northern Africa,Libya,LBY,"6,900,000"
120,Europe,Western Europe,Liechtenstein,LIE,"68,000,000"
121,Europe,Northern Europe,Lithuania,LTU,"3,500,000"
122,Europe,Western Europe,Luxembourg,LUX,"633,000"
123,Asia,Eastern Asia,Macao,MAC,"650,000"
124,Europe,Southern Europe,Macedonia (the former Yugoslav Republic of),MKD,"26,000,000"
125,Africa,Eastern Africa,Madagascar,MDG,"4,300,000"
126,Africa,Eastern Africa,Malawi,MWI,"25,800,000"
127,Asia,South-Eastern Asia,Malaysia,MYS,"53,800,000"
128,Asia,Southern Asia,Maldives,MDV,"540,000"
129,Africa,Western Africa,Mali,MLI,"30,000,000"
130,Europe,Southern Europe,Malta,MLT,"97,000,000"
131,Oceania,Micronesia,Marshall Islands,MHL,"59,000"
132,Americas,Caribbean,Martinique,MTQ,"6,900,000"
133,Africa,Western Africa,Mauritania,MRT,"83,200,000"
134,Africa,Eastern Africa,Mauritius,MUS,"1,300,000"
135,Africa,Eastern Africa,Mayotte,MYT,"4,800,000"
136,Americas,Central America,Mexico,MEX,"18,400,000"
137,Oceania,Micronesia,Micronesia (Federated States of),FSM,"164,000,000"
138,Europe,Eastern Europe,Moldova (Republic of),MDA,"3,300,000"
139,Europe,Western Europe,Monaco,MCO,"7,100,000"
140,Asia,Eastern Asia,Mongolia,MNG,"5,000,000"
141,Europe,Southern Europe,Montenegro,MNE,"622,000"
142,Americas,Caribbean,Montserrat,MSR,"5,000"
143,Africa,Northern Africa,Morocco,MAR,"6,800,000"
144,Africa,Eastern Africa,Mozambique,MOZ,"51,600,000"
145,Asia,South-Eastern Asia,Myanmar,MMR,"54,000,000"
146,Africa,Southern Africa,Namibia,NAM,"3,200,000"
147,Oceania,Micronesia,Nauru,NRU,"144,000,000"
148,Asia,Southern Asia,Nepal,NPL,"44,000,000"
149,Europe,Western Europe,Netherlands,NLD,"2,800,000"
150,Oceania,Melanesia,New Caledonia,NCL,"44,000,000"
151,Oceania,Australia and New Zealand,New Zealand,NZL,"84,000,000"
152,Americas,Central America,Nicaragua,NIC,"6,600,000"
153,Africa,Western Africa,Niger,NER,"35,000,000"
154,Africa,Western Africa,Nigeria,NGA,"31,000,000"
155,Oceania,Polynesia,Niue,NIU,"2,400,000"
156,Oceania,Australia and New Zealand,Norfolk Island,NFK,"20,300,000"
157,Oceania,Micronesia,Northern Mariana Islands,MNP,"58,000"
158,Europe,Northern Europe,Norway,NOR,"5,400,000"
159,Asia,Western Asia,Oman,OMN,"5,000,000"
160,Asia,Southern Asia,Pakistan,PAK,"331,000,000"
161,Oceania,Micronesia,Palau,PLW,"220,000,000"
162,Asia,Western Asia,"Palestine, State of",PSE,"5,100,000"
163,Americas,Central America,Panama,PAN,"8,700,000"
164,Oceania,Melanesia,Papua New Guinea,PNG,"9,000,000"
165,Americas,South America,Paraguay,PRY,"7,100,000"
166,Americas,South America,Peru,PER,"59,000,000"
167,Asia,South-Eastern Asia,Philippines,PHL,"13,100,000"
168,Oceania,Polynesia,Pitcairn,PCN,"50,000,000"
169,Europe,Eastern Europe,Poland,POL,"67,000,000"
170,Europe,Southern Europe,Portugal,PRT,"10,400,000"
171,Americas,Caribbean,Puerto Rico,PRI,"47,000,000"
172,Asia,Western Asia,Qatar,QAT,"3,500,000"
173,Africa,Eastern Africa,Réunion,REU,"859,000"
174,Europe,Eastern Europe,Romania,ROU,"24,000,000"
175,Europe,Eastern Europe,Russian Federation,RUS,"19,000,000"
176,Africa,Eastern Africa,Rwanda,RWA,"17,500,000"
177,Americas,Caribbean,Saint Barthélemy,BLM,"9,900"
178,Africa,Western Africa,"Saint Helena, Ascension and Tristan da Cunha",SHN,"6,000"
179,Americas,Caribbean,Saint Kitts and Nevis,KNA,"53,000"
180,Americas,Caribbean,Saint Lucia,LCA,"23,800,000"
181,Americas,Caribbean,Saint Martin (French part),MAF,"7,300,000"
182,Americas,Northern America,Saint Pierre and Miquelon,SPM,"5,700"
183,Americas,Caribbean,Saint Vincent and the Grenadines,VCT,"16,400,000"
184,Oceania,Polynesia,Samoa,WSM,"26,000,000"
185,Europe,Southern Europe,San Marino,SMR,"6,600,000"
186,Africa,Middle Africa,Sao Tome and Principe,STP,"33,000,000"
187,Asia,Western Asia,Saudi Arabia,SAU,"6,600,000"
188,Africa,Western Africa,Senegal,SEN,"2,300,000"
189,Europe,Southern Europe,Serbia,SRB,"6,900,000"
190,Africa,Eastern Africa,Seychelles,SYC,"98,000"
191,Africa,Western Africa,Sierra Leone,SLE,"7,900,000"
192,Asia,South-Eastern Asia,Singapore,SGP,"5,900,000"
193,Americas,Caribbean,Sint Maarten (Dutch part),SXM,"9,300,000"
194,Europe,Eastern Europe,Slovakia,SVK,"5,500,000"
195,Europe,Southern Europe,Slovenia,SVN,"276,000,000"
196,Oceania,Melanesia,Solomon Islands,SLB,"686,000"
197,Africa,Eastern Africa,Somalia,SOM,"19,100,000"
198,Africa,Southern Africa,South Africa,ZAF,"59,000,000"
199,Africa,Eastern Africa,South Sudan,SSD,"11,900,000"
200,Europe,Southern Europe,Spain,ESP,"47,000,000"
201,Asia,Southern Asia,Sri Lanka,LKA,"33,000,000"
202,Africa,Northern Africa,Sudan,SDN,"9,600,000"
203,Americas,South America,Suriname,SUR,"591,000"
204,Europe,Northern Europe,Svalbard and Jan Mayen,SJM,"4,000,000"
205,Africa,Southern Africa,Swaziland,SWZ,"1,200,000"
206,Europe,Northern Europe,Sweden,SWE,"10,700,000"
207,Europe,Western Europe,Switzerland,CHE,"8,700,000"
208,Asia,Western Asia,Syrian Arab Republic,SYR,"2,800,000"
209,Asia,Eastern Asia,"Taiwan, Province of China",TWN,"34,000,000"
210,Asia,Central Asia,Tajikistan,TJK,"9,500,000"
211,Africa,Eastern Africa,"Tanzania, United Republic of",TZA,"59,700,000"
212,Asia,South-Eastern Asia,Thailand,THA,"69,800,000"
213,Asia,South-Eastern Asia,Timor-Leste,TLS,"1,300,000"
214,Africa,Western Africa,Togo,TGO,"8,300,000"
215,Oceania,Polynesia,Tokelau,TKL,"2,000,000"
216,Oceania,Polynesia,Tonga,TON,"11,500,000"
217,Americas,Caribbean,Trinidad and Tobago,TTO,"1,900,000"
218,Africa,Northern Africa,Tunisia,TUN,"125,000,000"
219,Asia,Western Asia,Turkey,TUR,"84,000,000"
220,Asia,Central Asia,Turkmenistan,TKM,"6,000,000"
221,Americas,Caribbean,Turks and Caicos Islands,TCA,"69,800,000"
222,Oceania,Polynesia,Tuvalu,TUV,"15,000,000"
223,Africa,Eastern Africa,Uganda,UGA,"45,700,000"
224,Europe,Eastern Europe,Ukraine,UKR,"9,900,000"
225,Asia,Western Asia,United Arab Emirates,ARE,"9,900,000"
226,Europe,Northern Europe,United Kingdom of Great Britain and Northern I...,GBR,"68,000,000"
227,Americas,Northern America,United States of America,USA,"59,700,000"
228,Americas,South America,Uruguay,URY,"5,100,000"
229,Asia,Central Asia,Uzbekistan,UZB,"6,000,000"
230,Oceania,Melanesia,Vanuatu,VUT,"5,900,000"
231,Americas,South America,Venezuela (Bolivarian Republic of),VEN,"4,900,000"
232,Asia,South-Eastern Asia,Viet Nam,VNM,"97,000,000"
233,Americas,Caribbean,Virgin Islands (British),VGB,"5,800,000"
234,Americas,Caribbean,Virgin Islands (U.S.),VIR,"11,400,000"
235,Oceania,Polynesia,Wallis and Futuna,WLF,"15,900,000"
236,Africa,Northern Africa,Western Sahara,ESH,"597,000"
237,Asia,Western Asia,Yemen,YEM,"5,500,000"
238,Africa,Eastern Africa,Zambia,ZMB,"213,000,000"
239,Africa,Eastern Africa,Zimbabwe,ZWE,"19,100,000"

In [48]:
df_continent = df.set_index(['continent', 'sub_region']).sort_values(['continent', 'sub_region', 'country'], ascending = [False, True, True])

In [49]:
df_sub_region = df.set_index('sub_region').sort_values([ 'sub_region', 'country'], ascending = [True, True])

In [50]:
df_sub_region.loc["Caribbean"]

           continent                           country code_3     Unnamed: 4
sub_region
Caribbean   Americas                          Anguilla    AIA     2,100,000
Caribbean   Americas               Antigua and Barbuda    ATG        98,000
Caribbean   Americas                             Aruba    ABW    11,600,000
Caribbean   Americas                           Bahamas    BHS     7,500,000
Caribbean   Americas                          Barbados    BRB    44,000,000
Caribbean   Americas  Bonaire, Sint Eustatius and Saba    BES     4,300,000
Caribbean   Americas                    Cayman Islands    CYM        66,000
Caribbean   Americas                              Cuba    CUB   110,000,000
Caribbean   Americas                           Curaçao    CUW     2,600,000
Caribbean   Americas                          Dominica    DMA        72,000
Caribbean   Americas                Dominican Republic    DOM    11,200,000
Caribbean   Americas                           Grenada    GRD    16,700,000
Caribbean   Americas                        Guadeloupe    GLP     9,000,000
Caribbean   Americas                             Haiti    HTI   114,000,000
Caribbean   Americas                           Jamaica    JAM     3,700,000
Caribbean   Americas                        Martinique    MTQ     6,900,000
Caribbean   Americas                        Montserrat    MSR         5,000
Caribbean   Americas                       Puerto Rico    PRI    47,000,000
Caribbean   Americas                  Saint Barthélemy    BLM         9,900
Caribbean   Americas             Saint Kitts and Nevis    KNA        53,000
Caribbean   Americas                       Saint Lucia    LCA    23,800,000
Caribbean   Americas        Saint Martin (French part)    MAF     7,300,000
Caribbean   Americas  Saint Vincent and the Grenadines    VCT    16,400,000
Caribbean   Americas         Sint Maarten (Dutch part)    SXM     9,300,000
Caribbean   Americas               Trinidad and Tobago    TTO     1,900,000
Caribbean   Americas          Turks and Caicos Islands    TCA    69,800,000
Caribbean   Americas          Virgin Islands (British)    VGB     5,800,000
Caribbean   Americas             Virgin Islands (U.S.)    VIR    11,400,000

In [51]:
df_continent.loc['Asia']

,country,code_3,Unnamed: 4
sub_region,,,
Central Asia,Kazakhstan,KAZ,"22,000,000"
Central Asia,Kyrgyzstan,KGZ,"6,600,000"
Central Asia,Tajikistan,TJK,"9,500,000"
Central Asia,Turkmenistan,TKM,"6,000,000"
Central Asia,Uzbekistan,UZB,"6,000,000"
Eastern Asia,China,CHN,"1,412,000,000"
Eastern Asia,Hong Kong,HKG,"7,500,000"
Eastern Asia,Japan,JPN,"18,000,000"
Eastern Asia,Korea (Democratic People's Republic of),PRK,"38,000,000"
Eastern Asia,Korea (Republic of),KOR,"51,600,000"
Eastern Asia,Macao,MAC,"650,000"
Eastern Asia,Mongolia,MNG,"5,000,000"
Eastern Asia,"Taiwan, Province of China",TWN,"34,000,000"
South-Eastern Asia,Brunei Darussalam,BRN,"9,400,000"
South-Eastern Asia,Cambodia,KHM,"2,200,000"
South-Eastern Asia,Indonesia,IDN,"4,600,000"
South-Eastern Asia,Lao People's Democratic Republic,LAO,"7,300,000"
South-Eastern Asia,Malaysia,MYS,"53,800,000"
South-Eastern Asia,Myanmar,MMR,"54,000,000"
South-Eastern Asia,Philippines,PHL,"13,100,000"
South-Eastern Asia,Singapore,SGP,"5,900,000"
South-Eastern Asia,Thailand,THA,"69,800,000"
South-Eastern Asia,Timor-Leste,TLS,"1,300,000"
South-Eastern Asia,Viet Nam,VNM,"97,000,000"
Southern Asia,Afghanistan,AFG,"6,900,000"
Southern Asia,Bangladesh,BGD,"2,500,000"
Southern Asia,Bhutan,BTN,"771,000"
Southern Asia,India,IND,"1,400,000,000"
Southern Asia,Iran (Islamic Republic of),IRN,"84,000,000"
Southern Asia,Maldives,MDV,"540,000"
Southern Asia,Nepal,NPL,"44,000,000"
Southern Asia,Pakistan,PAK,"331,000,000"
Southern Asia,Sri Lanka,LKA,"33,000,000"
Western Asia,Armenia,ARM,"45,700,000"
Western Asia,Azerbaijan,AZE,"10,000,000"
Western Asia,Bahrain,BHR,"1,900,000"
Western Asia,Cyprus,CYP,"1,200,000"
Western Asia,Georgia,GEO,"5,400,000"
Western Asia,Iraq,IRQ,"89,000,000"
Western Asia,Israel,ISR,"9,300,000"
Western Asia,Jordan,JOR,"10,300,000"
Western Asia,Kuwait,KWT,"8,300,000"
Western Asia,Lebanon,LBN,"6,800,000"
Western Asia,Oman,OMN,"5,000,000"
Western Asia,"Palestine, State of",PSE,"5,100,000"
Western Asia,Qatar,QAT,"3,500,000"
Western Asia,Saudi Arabia,SAU,"6,600,000"
Western Asia,Syrian Arab Republic,SYR,"2,800,000"
Western Asia,Turkey,TUR,"84,000,000"
Western Asia,United Arab Emirates,ARE,"9,900,000"
Western Asia,Yemen,YEM,"5,500,000"

### Filtering Indexes with loc and iloc

In [53]:
df.set_index('country', inplace=True)
df

KeyError: "None of ['country'] are in the columns"

In [55]:
df.reset_index(inplace = True)
df

,index,country,continent,sub_region,code_3,Unnamed: 4
0,0,Afghanistan,Asia,Southern Asia,AFG,"6,900,000"
1,1,Åland Islands,Europe,Northern Europe,ALA,"5,500,000"
2,2,Albania,Europe,Southern Europe,ALB,"3,300,000"
3,3,Algeria,Africa,Northern Africa,DZA,"9,500,000"
4,4,American Samoa,Oceania,Polynesia,ASM,"55,000"
5,5,Andorra,Europe,Southern Europe,AND,"77,000"
6,6,Angola,Africa,Middle Africa,AGO,"54,000,000"
7,7,Anguilla,Americas,Caribbean,AIA,"2,100,000"
8,8,Antigua and Barbuda,Americas,Caribbean,ATG,"98,000"
9,9,Argentina,Americas,South America,ARG,"45,000,000"
10,10,Armenia,Asia,Western Asia,ARM,"45,700,000"
11,11,Aruba,Americas,Caribbean,ABW,"11,600,000"
12,12,Australia,Oceania,Australia and New Zealand,AUS,"36,000,000"
13,13,Austria,Europe,Western Europe,AUT,"9,000,000"
14,14,Azerbaijan,Asia,Western Asia,AZE,"10,000,000"
15,15,Bahamas,Americas,Caribbean,BHS,"7,500,000"
16,16,Bahrain,Asia,Western Asia,BHR,"1,900,000"
17,17,Bangladesh,Asia,Southern Asia,BGD,"2,500,000"
18,18,Barbados,Americas,Caribbean,BRB,"44,000,000"
19,19,Belarus,Europe,Eastern Europe,BLR,"9,400,000"
20,20,Belgium,Europe,Western Europe,BEL,"12,000,000"
21,21,Belize,Americas,Central America,BLZ,"9,000,000"
22,22,Benin,Africa,Western Africa,BEN,"17,400,000"
23,23,Bermuda,Americas,Northern America,BMU,"64,000"
24,24,Bhutan,Asia,Southern Asia,BTN,"771,000"
25,25,Bolivia (Plurinational State of),Americas,South America,BOL,"12,900,000"
26,26,"Bonaire, Sint Eustatius and Saba",Americas,Caribbean,BES,"4,300,000"
27,27,Bosnia and Herzegovina,Europe,Southern Europe,BIH,"5,000,000"
28,28,Botswana,Africa,Southern Africa,BWA,"29,000,000"
29,29,Brazil,Americas,South America,BRA,"32,700,000"
30,30,Brunei Darussalam,Asia,South-Eastern Asia,BRN,"9,400,000"
31,31,Bulgaria,Europe,Eastern Europe,BGR,"6,900,000"
32,32,Burkina Faso,Africa,Western Africa,BFA,"31,000,000"
33,33,Burundi,Africa,Eastern Africa,BDI,"128,000,000"
34,34,Cabo Verde,Africa,Western Africa,CPV,"556,000"
35,35,Cambodia,Asia,South-Eastern Asia,KHM,"2,200,000"
36,36,Cameroon,Africa,Middle Africa,CMR,"38,000,000"
37,37,Canada,Americas,Northern America,CAN,"60,000,000"
38,38,Cayman Islands,Americas,Caribbean,CYM,"66,000"
39,39,Central African Republic,Africa,Middle Africa,CAF,"84,000,000"
40,40,Chad,Africa,Middle Africa,TCD,"2,100,000"
41,41,Chile,Americas,South America,CHL,"25,000,000"
42,42,China,Asia,Eastern Asia,CHN,"1,412,000,000"
43,43,Colombia,Americas,South America,COL,"51,000,000"
44,44,Comoros,Africa,Eastern Africa,COM,"870,000"
45,45,Congo,Africa,Middle Africa,COG,"5,500,000"
46,46,Congo (Democratic Republic of the),Africa,Middle Africa,COD,"89,000,000"
47,47,Cook Islands,Oceania,Polynesia,COK,"206,000,000"
48,48,Costa Rica,Americas,Central America,CRI,"5,100,000"
49,49,Côte d'Ivoire,Africa,Western Africa,CIV,"38,000,000"
50,50,Croatia,Europe,Southern Europe,HRV,"7,900,000"
51,51,Cuba,Americas,Caribbean,CUB,"110,000,000"
52,52,Curaçao,Americas,Caribbean,CUW,"2,600,000"
53,53,Cyprus,Asia,Western Asia,CYP,"1,200,000"
54,54,Czech Republic,Europe,Eastern Europe,CZE,"102,000,000"
55,55,Denmark,Europe,Northern Europe,DNK,"5,800,000"
56,56,Djibouti,Africa,Eastern Africa,DJI,"988,000"
57,57,Dominica,Americas,Caribbean,DMA,"72,000"
58,58,Dominican Republic,Americas,Caribbean,DOM,"11,200,000"
59,59,Ecuador,Americas,South America,ECU,"2,900,000"
60,60,Egypt,Africa,Northern Africa,EGY,"11,300,000"
61,61,El Salvador,Americas,Central America,SLV,"6,500,000"
62,62,Equatorial Guinea,Africa,Middle Africa,GNQ,"1,700,000"
63,63,Eritrea,Africa,Eastern Africa,ERI,"5,100,000"
64,64,Estonia,Europe,Northern Europe,EST,"1,300,000"
65,65,Ethiopia,Africa,Eastern Africa,ETH,"16,700,000"
66,66,Falkland Islands (Malvinas),Americas,South America,FLK,"5,500,000"
67,67,Faroe Islands,Europe,Northern Europe,FRO,"49,000"
68,68,Fiji,Oceania,Melanesia,FJI,"896,000"
69,69,Finland,Europe,Northern Europe,FIN,"5,500,000"
70,70,France,Europe,Western Europe,FRA,"67,000,000"
71,71,French Guiana,Americas,South America,GUF,"45,000,000"
72,72,French Polynesia,Oceania,Polynesia,PYF,"40,000,000"
73,73,Gabon,Africa,Middle Africa,GAB,"28,000,000"
74,74,Gambia,Africa,Western Africa,GMB,"3,000,000"
75,75,Georgia,Asia,Western Asia,GEO,"5,400,000"
76,76,Germany,Europe,Western Europe,DEU,"83,200,000"
77,77,Ghana,Africa,Western Africa,GHA,"51,000,000"
78,78,Gibraltar,Europe,Southern Europe,GIB,"6,500,000"
79,79,Greece,Europe,Southern Europe,GRC,"10,800,000"
80,80,Greenland,Americas,Northern America,GRL,"56,000"
81,81,Grenada,Americas,Caribbean,GRD,"16,700,000"
82,82,Guadeloupe,Americas,Caribbean,GLP,"9,000,000"
83,83,Guam,Oceania,Micronesia,GUM,"2,800,000"
84,84,Guatemala,Americas,Central America,GTM,"21,000,000"
85,85,Guernsey,Europe,Northern Europe,GGY,"63,000"
86,86,Guinea,Africa,Western Africa,GIN,"18,700,000"
87,87,Guinea-Bissau,Africa,Western Africa,GNB,"10,000,000"
88,88,Guyana,Americas,South America,GUY,"787,000"
89,89,Haiti,Americas,Caribbean,HTI,"114,000,000"
90,90,Holy See,Europe,Southern Europe,VAT,800
91,91,Honduras,Americas,Central America,HND,"10,000,000"
92,92,Hong Kong,Asia,Eastern Asia,HKG,"7,500,000"
93,93,Hungary,Europe,Eastern Europe,HUN,"9,600,000"
94,94,Iceland,Europe,Northern Europe,ISL,"6,900,000"
95,95,India,Asia,Southern Asia,IND,"1,400,000,000"
96,96,Indonesia,Asia,South-Eastern Asia,IDN,"4,600,000"
97,97,Iran (Islamic Republic of),Asia,Southern Asia,IRN,"84,000,000"
98,98,Iraq,Asia,Western Asia,IRQ,"89,000,000"
99,99,Ireland,Europe,Northern Europe,IRL,"5,000,000"
100,100,Isle of Man,Europe,Northern Europe,IMN,"85,000"
101,101,Israel,Asia,Western Asia,ISR,"9,300,000"
102,102,Italy,Europe,Southern Europe,ITA,"60,000,000"
103,103,Jamaica,Americas,Caribbean,JAM,"3,700,000"
104,104,Japan,Asia,Eastern Asia,JPN,"18,000,000"
105,105,Jersey,Europe,Northern Europe,JEY,"11,800,000"
106,106,Jordan,Asia,Western Asia,JOR,"10,300,000"
107,107,Kazakhstan,Asia,Central Asia,KAZ,"22,000,000"
108,108,Kenya,Africa,Eastern Africa,KEN,"53,800,000"
109,109,Kiribati,Oceania,Micronesia,KIR,"17,600,000"
110,110,Korea (Democratic People's Republic of),Asia,Eastern Asia,PRK,"38,000,000"
111,111,Korea (Republic of),Asia,Eastern Asia,KOR,"51,600,000"
112,112,Kuwait,Asia,Western Asia,KWT,"8,300,000"
113,113,Kyrgyzstan,Asia,Central Asia,KGZ,"6,600,000"
114,114,Lao People's Democratic Republic,Asia,South-Eastern Asia,LAO,"7,300,000"
115,115,Latvia,Europe,Northern Europe,LVA,"10,000,000"
116,116,Lebanon,Asia,Western Asia,LBN,"6,800,000"
117,117,Lesotho,Africa,Southern Africa,LSO,"27,700,000"
118,118,Liberia,Africa,Western Africa,LBR,"5,000,000"
119,119,Libya,Africa,Northern Africa,LBY,"6,900,000"
120,120,Liechtenstein,Europe,Western Europe,LIE,"68,000,000"
121,121,Lithuania,Europe,Northern Europe,LTU,"3,500,000"
122,122,Luxembourg,Europe,Western Europe,LUX,"633,000"
123,123,Macao,Asia,Eastern Asia,MAC,"650,000"
124,124,Macedonia (the former Yugoslav Republic of),Europe,Southern Europe,MKD,"26,000,000"
125,125,Madagascar,Africa,Eastern Africa,MDG,"4,300,000"
126,126,Malawi,Africa,Eastern Africa,MWI,"25,800,000"
127,127,Malaysia,Asia,South-Eastern Asia,MYS,"53,800,000"
128,128,Maldives,Asia,Southern Asia,MDV,"540,000"
129,129,Mali,Africa,Western Africa,MLI,"30,000,000"
130,130,Malta,Europe,Southern Europe,MLT,"97,000,000"
131,131,Marshall Islands,Oceania,Micronesia,MHL,"59,000"
132,132,Martinique,Americas,Caribbean,MTQ,"6,900,000"
133,133,Mauritania,Africa,Western Africa,MRT,"83,200,000"
134,134,Mauritius,Africa,Eastern Africa,MUS,"1,300,000"
135,135,Mayotte,Africa,Eastern Africa,MYT,"4,800,000"
136,136,Mexico,Americas,Central America,MEX,"18,400,000"
137,137,Micronesia (Federated States of),Oceania,Micronesia,FSM,"164,000,000"
138,138,Moldova (Republic of),Europe,Eastern Europe,MDA,"3,300,000"
139,139,Monaco,Europe,Western Europe,MCO,"7,100,000"
140,140,Mongolia,Asia,Eastern Asia,MNG,"5,000,000"
141,141,Montenegro,Europe,Southern Europe,MNE,"622,000"
142,142,Montserrat,Americas,Caribbean,MSR,"5,000"
143,143,Morocco,Africa,Northern Africa,MAR,"6,800,000"
144,144,Mozambique,Africa,Eastern Africa,MOZ,"51,600,000"
145,145,Myanmar,Asia,South-Eastern Asia,MMR,"54,000,000"
146,146,Namibia,Africa,Southern Africa,NAM,"3,200,000"
147,147,Nauru,Oceania,Micronesia,NRU,"144,000,000"
148,148,Nepal,Asia,Southern Asia,NPL,"44,000,000"
149,149,Netherlands,Europe,Western Europe,NLD,"2,800,000"
150,150,New Caledonia,Oceania,Melanesia,NCL,"44,000,000"
151,151,New Zealand,Oceania,Australia and New Zealand,NZL,"84,000,000"
152,152,Nicaragua,Americas,Central America,NIC,"6,600,000"
153,153,Niger,Africa,Western Africa,NER,"35,000,000"
154,154,Nigeria,Africa,Western Africa,NGA,"31,000,000"
155,155,Niue,Oceania,Polynesia,NIU,"2,400,000"
156,156,Norfolk Island,Oceania,Australia and New Zealand,NFK,"20,300,000"
157,157,Northern Mariana Islands,Oceania,Micronesia,MNP,"58,000"
158,158,Norway,Europe,Northern Europe,NOR,"5,400,000"
159,159,Oman,Asia,Western Asia,OMN,"5,000,000"
160,160,Pakistan,Asia,Southern Asia,PAK,"331,000,000"
161,161,Palau,Oceania,Micronesia,PLW,"220,000,000"
162,162,"Palestine, State of",Asia,Western Asia,PSE,"5,100,000"
163,163,Panama,Americas,Central America,PAN,"8,700,000"
164,164,Papua New Guinea,Oceania,Melanesia,PNG,"9,000,000"
165,165,Paraguay,Americas,South America,PRY,"7,100,000"
166,166,Peru,Americas,South America,PER,"59,000,000"
167,167,Philippines,Asia,South-Eastern Asia,PHL,"13,100,000"
168,168,Pitcairn,Oceania,Polynesia,PCN,"50,000,000"
169,169,Poland,Europe,Eastern Europe,POL,"67,000,000"
170,170,Portugal,Europe,Southern Europe,PRT,"10,400,000"
171,171,Puerto Rico,Americas,Caribbean,PRI,"47,000,000"
172,172,Qatar,Asia,Western Asia,QAT,"3,500,000"
173,173,Réunion,Africa,Eastern Africa,REU,"859,000"
174,174,Romania,Europe,Eastern Europe,ROU,"24,000,000"
175,175,Russian Federation,Europe,Eastern Europe,RUS,"19,000,000"
176,176,Rwanda,Africa,Eastern Africa,RWA,"17,500,000"
177,177,Saint Barthélemy,Americas,Caribbean,BLM,"9,900"
178,178,"Saint Helena, Ascension and Tristan da Cunha",Africa,Western Africa,SHN,"6,000"
179,179,Saint Kitts and Nevis,Americas,Caribbean,KNA,"53,000"
180,180,Saint Lucia,Americas,Caribbean,LCA,"23,800,000"
181,181,Saint Martin (French part),Americas,Caribbean,MAF,"7,300,000"
182,182,Saint Pierre and Miquelon,Americas,Northern America,SPM,"5,700"
183,183,Saint Vincent and the Grenadines,Americas,Caribbean,VCT,"16,400,000"
184,184,Samoa,Oceania,Polynesia,WSM,"26,000,000"
185,185,San Marino,Europe,Southern Europe,SMR,"6,600,000"
186,186,Sao Tome and Principe,Africa,Middle Africa,STP,"33,000,000"
187,187,Saudi Arabia,Asia,Western Asia,SAU,"6,600,000"
188,188,Senegal,Africa,Western Africa,SEN,"2,300,000"
189,189,Serbia,Europe,Southern Europe,SRB,"6,900,000"
190,190,Seychelles,Africa,Eastern Africa,SYC,"98,000"
191,191,Sierra Leone,Africa,Western Africa,SLE,"7,900,000"
192,192,Singapore,Asia,South-Eastern Asia,SGP,"5,900,000"
193,193,Sint Maarten (Dutch part),Americas,Caribbean,SXM,"9,300,000"
194,194,Slovakia,Europe,Eastern Europe,SVK,"5,500,000"
195,195,Slovenia,Europe,Southern Europe,SVN,"276,000,000"
196,196,Solomon Islands,Oceania,Melanesia,SLB,"686,000"
197,197,Somalia,Africa,Eastern Africa,SOM,"19,100,000"
198,198,South Africa,Africa,Southern Africa,ZAF,"59,000,000"
199,199,South Sudan,Africa,Eastern Africa,SSD,"11,900,000"
200,200,Spain,Europe,Southern Europe,ESP,"47,000,000"
201,201,Sri Lanka,Asia,Southern Asia,LKA,"33,000,000"
202,202,Sudan,Africa,Northern Africa,SDN,"9,600,000"
203,203,Suriname,Americas,South America,SUR,"591,000"
204,204,Svalbard and Jan Mayen,Europe,Northern Europe,SJM,"4,000,000"
205,205,Swaziland,Africa,Southern Africa,SWZ,"1,200,000"
206,206,Sweden,Europe,Northern Europe,SWE,"10,700,000"
207,207,Switzerland,Europe,Western Europe,CHE,"8,700,000"
208,208,Syrian Arab Republic,Asia,Western Asia,SYR,"2,800,000"
209,209,"Taiwan, Province of China",Asia,Eastern Asia,TWN,"34,000,000"
210,210,Tajikistan,Asia,Central Asia,TJK,"9,500,000"
211,211,"Tanzania, United Republic of",Africa,Eastern Africa,TZA,"59,700,000"
212,212,Thailand,Asia,South-Eastern Asia,THA,"69,800,000"
213,213,Timor-Leste,Asia,South-Eastern Asia,TLS,"1,300,000"
214,214,Togo,Africa,Western Africa,TGO,"8,300,000"
215,215,Tokelau,Oceania,Polynesia,TKL,"2,000,000"
216,216,Tonga,Oceania,Polynesia,TON,"11,500,000"
217,217,Trinidad and Tobago,Americas,Caribbean,TTO,"1,900,000"
218,218,Tunisia,Africa,Northern Africa,TUN,"125,000,000"
219,219,Turkey,Asia,Western Asia,TUR,"84,000,000"
220,220,Turkmenistan,Asia,Central Asia,TKM,"6,000,000"
221,221,Turks and Caicos Islands,Americas,Caribbean,TCA,"69,800,000"
222,222,Tuvalu,Oceania,Polynesia,TUV,"15,000,000"
223,223,Uganda,Africa,Eastern Africa,UGA,"45,700,000"
224,224,Ukraine,Europe,Eastern Europe,UKR,"9,900,000"
225,225,United Arab Emirates,Asia,Western Asia,ARE,"9,900,000"
226,226,United Kingdom of Great Britain and Northern I...,Europe,Northern Europe,GBR,"68,000,000"
227,227,United States of America,Americas,Northern America,USA,"59,700,000"
228,228,Uruguay,Americas,South America,URY,"5,100,000"
229,229,Uzbekistan,Asia,Central Asia,UZB,"6,000,000"
230,230,Vanuatu,Oceania,Melanesia,VUT,"5,900,000"
231,231,Venezuela (Bolivarian Republic of),Americas,South America,VEN,"4,900,000"
232,232,Viet Nam,Asia,South-Eastern Asia,VNM,"97,000,000"
233,233,Virgin Islands (British),Americas,Caribbean,VGB,"5,800,000"
234,234,Virgin Islands (U.S.),Americas,Caribbean,VIR,"11,400,000"
235,235,Wallis and Futuna,Oceania,Polynesia,WLF,"15,900,000"
236,236,Western Sahara,Africa,Northern Africa,ESH,"597,000"
237,237,Yemen,Asia,Western Asia,YEM,"5,500,000"
238,238,Zambia,Africa,Eastern Africa,ZMB,"213,000,000"
239,239,Zimbabwe,Africa,Eastern Africa,ZWE,"19,100,000"

In [57]:
df.set_index(["continent", "country"], inplace = True)

In [65]:
df.iloc[0]

index                     0
sub_region    Southern Asia
code_3                  AFG
Unnamed: 4       6,900,000
Name: (Asia, Afghanistan), dtype: object